name: Publish to npm
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
        run: yarn install
      - name: Version patch
        run: yarn version patch
      - name: Publish 
        run: yarn publish

